### ISSUE TITLE
集成3.0.1alpha1出现crash

### ISSUE THREAD

**Issue by qiushihang** [android-notes/SwissArmyKnife#23]
java.lang.RuntimeException: java.lang.NoSuchMethodException: android.graphics.RenderNode.setLeftTopRightBottom [int, int, int, int]
        at com.wanjian.sak.system.rendernode.RenderNodeV29Impl.beginRecording(RenderNodeV29Impl.java:30)
        at com.wanjian.sak.system.rendernode.RenderNodeV29Impl.beginRecording(RenderNodeV29Impl.java:9)
        at com.wanjian.sak.layer.Layer.invalidate(Layer.java:58)
        at com.wanjian.sak.layer.impl.GridLayer.onAttach(GridLayer.java:22)
        at com.wanjian.sak.layer.Layer.attach(Layer.java:37)
        at com.wanjian.sak.layer.LayerRoot.<init>(LayerRoot.java:108)
        at com.wanjian.sak.layer.LayerRoot.create(LayerRoot.java:26)
        at com.wanjian.sak.Scaffold$1$1.run(Scaffold.java:36)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by HaimingWei213** [comment]
hi 你这边有出现android 11 启动崩溃问题呢

**Comment by StephenGiant** [comment]
需要使用 me.weishu.reflection.Reflection.unseal(this);

**Comment by StephenGiant** [comment]
亲测 使用了Reflection.unseal(this)也没用。。。

**Comment by gaoyangcr7** [comment]
有人解决吗

**Comment by android-notes** [comment]
已修复
