### ISSUE TITLE
Android 11 启动崩溃

### ISSUE THREAD

**Issue by HaimingWei213** [android-notes/SwissArmyKnife#24]
11-15 12:43:58.620 28639 28639 E AndroidRuntime: FATAL EXCEPTION: main
11-15 12:43:58.620 28639 28639 E AndroidRuntime: Process: com.wanjian.sak.demo, PID: 28639
11-15 12:43:58.620 28639 28639 E AndroidRuntime: java.lang.RuntimeException: InputChannel is not initialized.
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at android.view.InputEventReceiver.nativeInit(Native Method)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at android.view.InputEventReceiver.<init>(InputEventReceiver.java:79)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at com.wanjian.sak.system.input.InputEventReceiverV29Impl.<init>(InputEventReceiverV29Impl.java:21)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at com.wanjian.sak.system.input.InputEventReceiverCompact.get(InputEventReceiverCompact.java:23)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at com.wanjian.sak.Scaffold.observerInputEvent(Scaffold.java:55)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at com.wanjian.sak.Scaffold.access$200(Scaffold.java:21)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at com.wanjian.sak.Scaffold$1$1.run(Scaffold.java:39)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:257)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8331)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1032)

**Comment by HaimingWei213** [comment]
11-15 12:43:58.620 28639 28639 E AndroidRuntime: FATAL EXCEPTION: main
11-15 12:43:58.620 28639 28639 E AndroidRuntime: Process: com.wanjian.sak.demo, PID: 28639
11-15 12:43:58.620 28639 28639 E AndroidRuntime: java.lang.RuntimeException: InputChannel is not initialized.
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at android.view.InputEventReceiver.nativeInit(Native Method)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at android.view.InputEventReceiver.<init>(InputEventReceiver.java:79)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at com.wanjian.sak.system.input.InputEventReceiverV29Impl.<init>(InputEventReceiverV29Impl.java:21)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at com.wanjian.sak.system.input.InputEventReceiverCompact.get(InputEventReceiverCompact.java:23)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at com.wanjian.sak.Scaffold.observerInputEvent(Scaffold.java:55)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at com.wanjian.sak.Scaffold.access$200(Scaffold.java:21)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at com.wanjian.sak.Scaffold$1$1.run(Scaffold.java:39)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:257)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8331)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
11-15 12:43:58.620 28639 28639 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1032)

**Comment by spiritedRunning** [comment]
红米Android 11 也是崩溃
`2022-01-09 18:50:26.875 24035-24035/? E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/system/app/XiaomiAccount/XiaomiAccount.apk"],nativeLibraryDirectories=[/system/app/XiaomiAccount/lib/arm64, /system/app/XiaomiAccount/XiaomiAccount.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /system/priv-app/RtMiCloudSDK/RtMiCloudSDK.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:266)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:911)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:964)
        at android.app.LoadedApk.getResources(LoadedApk.java:1196)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2672)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2664)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6903)
        at android.app.ActivityThread.access$1600(ActivityThread.java:265)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2042)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8087)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)`

**Comment by spiritedRunning** [comment]
`
2022-01-09 18:50:26.875 24035-24035/? E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/system/app/XiaomiAccount/XiaomiAccount.apk"],nativeLibraryDirectories=[/system/app/XiaomiAccount/lib/arm64, /system/app/XiaomiAccount/XiaomiAccount.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /system/priv-app/RtMiCloudSDK/RtMiCloudSDK.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:266)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:911)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:964)
        at android.app.LoadedApk.getResources(LoadedApk.java:1196)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2672)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2664)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6903)
        at android.app.ActivityThread.access$1600(ActivityThread.java:265)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2042)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8087)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
`

**Comment by spiritedRunning** [comment]
也是11 ，同样崩溃

 java.lang.RuntimeException: java.lang.NoSuchMethodException: android.graphics.RenderNode.setLeftTopRightBottom [int, int, int, int]
        at com.wanjian.sak.system.rendernode.RenderNodeV29Impl.beginRecording(RenderNodeV29Impl.java:30)
        at com.wanjian.sak.system.rendernode.RenderNodeV29Impl.beginRecording(RenderNodeV29Impl.java:9)
        at com.wanjian.sak.layer.Layer.invalidate(Layer.java:58)
        at com.wanjian.sak.layer.impl.GridLayer.onAttach(GridLayer.java:22)
        at com.wanjian.sak.layer.Layer.attach(Layer.java:37)
        at com.wanjian.sak.layer.LayerRoot.<init>(LayerRoot.java:108)
        at com.wanjian.sak.layer.LayerRoot.create(LayerRoot.java:26)
        at com.wanjian.sak.Scaffold$1$1.run(Scaffold.java:36)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NoSuchMethodException: android.graphics.RenderNode.setLeftTopRightBottom [int, int, int, int]
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getDeclaredMethod(Class.java:2050)
        at com.wanjian.sak.system.rendernode.RenderNodeV29Impl.beginRecording(RenderNodeV29Impl.java:26)
        at com.wanjian.sak.system.rendernode.RenderNodeV29Impl.beginRecording(RenderNodeV29Impl.java:9) 
        at com.wanjian.sak.layer.Layer.invalidate(Layer.java:58) 
        at com.wanjian.sak.layer.impl.GridLayer.onAttach(GridLayer.java:22) 
        at com.wanjian.sak.layer.Layer.attach(Layer.java:37) 
        at com.wanjian.sak.layer.LayerRoot.<init>(LayerRoot.java:108) 
        at com.wanjian.sak.layer.LayerRoot.create(LayerRoot.java:26) 
        at com.wanjian.sak.Scaffold$1$1.run(Scaffold.java:36) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2022-01-10 18:50:23.217 626-626/? E/lowmemorykiller: Error writing /proc/10528/oom_score_adj; errno=22

**Comment by android-notes** [comment]
已修复
